### ISSUE TITLE
Add command to update metadata for archived products

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/muninn#10]
This command line operation should update the metadata for all products in the archive (or only those matching a query provided as parameter).

This is useful for situations where the plugin was modified and we need to rebuild the metadata.

**Comment by svniemeijer** [comment]
We may also want a 'dry run' mode that will only show the differences (without applying them).

**Comment by bruno-rino** [comment]
Solved by b2cd94d
A 'dry run' mode is to be addressed separately as #26
