### ISSUE TITLE
Introduce extension mechanism for muninn-pull transfer protocols

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/muninn#13]
This would allow plugins to provide their own transfer protocol mechanisms.

As part of this, we should also move the 'ecmwfmars' protocol that is now part of muninn itself into such an extension. Only the basic file/ftp/http/https protocols should remain.

**Comment by brussee** [comment]
Take a look at Twisted, I think it is great to use for the download mechanisms and it also provides a plugin framework http://twistedmatrix.com/documents/current/core/howto/plugin.html

**Comment by bruno-rino** [comment]
solved by 6a105fb
