### ISSUE TITLE
Python3: string-typing issues in ewkb.py

### ISSUE THREAD

**Issue by stefanlinden** [stcorp/muninn#18]
This issue is regarding the `visit_*()` methods part of `EWKBEncoder` defined in `backends/ewkb.py`. In my context, they are being used when inserting new entries into the catalog, using the PostgreSQL backend.
Each of these methods contain a line similar to the following:

```python
ewkb += "".join([self.visit(ring, False) for ring in visitable])
```
Occasionally, the inline `for` loop calling `self.visit()` seems to return byte strings. In many other contexts, it returns an ASCII string. When the former's the case, it breaks the `"".join(...)` in Python 3, as it cannot combine different string types in this operation.

The recommendation is to unify the output of `visit()` to always return the same string type (bytes, ASCII or UTF-8).

**Comment by svniemeijer** [comment]
Fixed in b4f9178
