### ISSUE TITLE
Add introspection on available namespaces in archive

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/muninn#23]
It would be useful to have a way to retrieve the list of available namespaces, together with fields and types, for a muninn archive via a command line call.

Additional variations of this interface might also allow retrieving of the SQL calls to create the database tables for these namespaces (either a for single namespace or for the full set of tables including relations/tags/etc.).

**Comment by bruno-rino** [comment]
The newly created `muninn-info` tool retrieves the list of available namespaces.

Retrieving of the SQL calls is still TODO

**Comment by bruno-rino** [comment]
Remaining functionality will be addressed as #25
