### ISSUE TITLE
Extend muninn-info with SQL table creation calls

### ISSUE THREAD

**Issue by bruno-rino** [stcorp/muninn#25]
Add an option to retrieve the SQL calls to create the database tables for these namespaces (either for a single namespace or for the full set of tables including relations/tags/etc.).

**Comment by bruno-rino** [comment]
Note that we can already get the SQL calls (although this always gets the full set): 
```
muninn-prepare --dry-run
```

**Comment by svniemeijer** [comment]
Indeed. That suffices. So no need to do anything else in my opinion.
