### ISSUE TITLE
sqlite: covers(geometry) returns true when arguments are null

### ISSUE THREAD

**Issue by bruno-rino** [stcorp/muninn#29]
Using the sqlite backend, `covers(core.footprint, POINT (5.0 52.0))` returns:
- products where the point is contained in the footprint
- products where the footprint is set to NULL

The second set of matches is not returned when using the postgres backend, which I presume is the desired behavior.

The source of the issue is that in spatialite, ST_Contains returns -1 (a truthy value) when passed NULL arguments (see https://www.gaia-gis.it/gaia-sins/spatialite-sql-4.2.0.html):
> The return type is Integer, with a return value of 1 for TRUE, 0 for FALSE, and –1 for UNKNOWN corresponding to a function invocation on NULL arguments;

**Comment by svniemeijer** [comment]
Fixed in 6a9fe86d582868afa6acea7026a657fc3ea00c8e
